[package]
name = "aurora-watch"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"

#quick-xml = "0.26"
serde-xml-rs = "0.5"
