[package]
name = "aurora-watch"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"

serde-xml-rs = "0.5"
env_logger = "0.11"
log = "0.4"
thiserror = "2"
hyper = "0.14"
